package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubscriptionsEmailAddressParams creates a new GetSubscriptionsEmailAddressParams object
// with the default values initialized.
func NewGetSubscriptionsEmailAddressParams() GetSubscriptionsEmailAddressParams {
	var ()
	return GetSubscriptionsEmailAddressParams{}
}

// GetSubscriptionsEmailAddressParams contains all the bound params for the get subscriptions email address operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSubscriptionsEmailAddress
type GetSubscriptionsEmailAddressParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Guest email address
	  Required: true
	  Pattern: ^.*\@.*\..*
	  In: path
	*/
	EmailAddress string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetSubscriptionsEmailAddressParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rEmailAddress, rhkEmailAddress, _ := route.Params.GetOK("emailAddress")
	if err := o.bindEmailAddress(rEmailAddress, rhkEmailAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSubscriptionsEmailAddressParams) bindEmailAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.EmailAddress = raw

	if err := o.validateEmailAddress(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetSubscriptionsEmailAddressParams) validateEmailAddress(formats strfmt.Registry) error {

	if err := validate.Pattern("emailAddress", "path", string(o.EmailAddress), `^.*\@.*\..*`); err != nil {
		return err
	}

	return nil
}
