package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kcraybould/subscriptions/models"
)

/*PutSubscriptionsEmailAddressNoContent Success

swagger:response putSubscriptionsEmailAddressNoContent
*/
type PutSubscriptionsEmailAddressNoContent struct {
}

// NewPutSubscriptionsEmailAddressNoContent creates PutSubscriptionsEmailAddressNoContent with default headers values
func NewPutSubscriptionsEmailAddressNoContent() *PutSubscriptionsEmailAddressNoContent {
	return &PutSubscriptionsEmailAddressNoContent{}
}

// WriteResponse to the client
func (o *PutSubscriptionsEmailAddressNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*PutSubscriptionsEmailAddressBadRequest Bad Request

swagger:response putSubscriptionsEmailAddressBadRequest
*/
type PutSubscriptionsEmailAddressBadRequest struct {

	// In: body
	Payload *models.ErrorDetail `json:"body,omitempty"`
}

// NewPutSubscriptionsEmailAddressBadRequest creates PutSubscriptionsEmailAddressBadRequest with default headers values
func NewPutSubscriptionsEmailAddressBadRequest() *PutSubscriptionsEmailAddressBadRequest {
	return &PutSubscriptionsEmailAddressBadRequest{}
}

// WithPayload adds the payload to the put subscriptions email address bad request response
func (o *PutSubscriptionsEmailAddressBadRequest) WithPayload(payload *models.ErrorDetail) *PutSubscriptionsEmailAddressBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put subscriptions email address bad request response
func (o *PutSubscriptionsEmailAddressBadRequest) SetPayload(payload *models.ErrorDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutSubscriptionsEmailAddressBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutSubscriptionsEmailAddressNotFound Not Found

swagger:response putSubscriptionsEmailAddressNotFound
*/
type PutSubscriptionsEmailAddressNotFound struct {
}

// NewPutSubscriptionsEmailAddressNotFound creates PutSubscriptionsEmailAddressNotFound with default headers values
func NewPutSubscriptionsEmailAddressNotFound() *PutSubscriptionsEmailAddressNotFound {
	return &PutSubscriptionsEmailAddressNotFound{}
}

// WriteResponse to the client
func (o *PutSubscriptionsEmailAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
