package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kcraybould/subscriptions/models"
)

// NewPutSubscriptionsEmailAddressParams creates a new PutSubscriptionsEmailAddressParams object
// with the default values initialized.
func NewPutSubscriptionsEmailAddressParams() PutSubscriptionsEmailAddressParams {
	var ()
	return PutSubscriptionsEmailAddressParams{}
}

// PutSubscriptionsEmailAddressParams contains all the bound params for the put subscriptions email address operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutSubscriptionsEmailAddress
type PutSubscriptionsEmailAddressParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Guest email address
	  Required: true
	  Pattern: ^.*\@.*\..*
	  In: path
	*/
	EmailAddress string
	/*subscription information
	  Required: true
	  In: body
	*/
	Subscriber *models.Subscriber
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutSubscriptionsEmailAddressParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rEmailAddress, rhkEmailAddress, _ := route.Params.GetOK("emailAddress")
	if err := o.bindEmailAddress(rEmailAddress, rhkEmailAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Subscriber
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("subscriber", "body"))
			} else {
				res = append(res, errors.NewParseError("subscriber", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Subscriber = &body
			}
		}

	} else {
		res = append(res, errors.Required("subscriber", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutSubscriptionsEmailAddressParams) bindEmailAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.EmailAddress = raw

	if err := o.validateEmailAddress(formats); err != nil {
		return err
	}

	return nil
}

func (o *PutSubscriptionsEmailAddressParams) validateEmailAddress(formats strfmt.Registry) error {

	if err := validate.Pattern("emailAddress", "path", string(o.EmailAddress), `^.*\@.*\..*`); err != nil {
		return err
	}

	return nil
}
