package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*SubscriptionOptOuts subscription opt outs

swagger:model SubscriptionOptOuts
*/
type SubscriptionOptOuts struct {

	/* Opt out of all marketing and survey emails
	 */
	Global bool `json:"global,omitempty"`

	/* Opt out of all marketing emails
	 */
	Marketing bool `json:"marketing,omitempty"`

	/* Opt out of all survey emails
	 */
	Survey bool `json:"survey,omitempty"`
}

// Validate validates this subscription opt outs
func (m *SubscriptionOptOuts) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
